FROM golang:latest AS builder

RUN apt-get update && \
    apt-get install -y build-essential git && \
    git clone https://github.com/naiba/nezha.git /opt/nezha && \
    cd /opt/nezha/cmd/agent && \
    go build -a -trimpath -ldflags="-s -w" -o /opt/agent


FROM debian:stable-slim

ENV TZ="Asia/Shanghai"

RUN apt-get update && \
    apt-get install -y --no-install-recommends tzdata ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /opt/agent /nezha/

CMD ["/nezha/agent"]