FROM golang:latest AS builder

RUN apt-get update && \
    apt-get install -y build-essential git && \
    git clone https://github.com/nezhahq/agent.git /opt/nezha && \
    cd /opt/nezha && \
    export VERSION=$(git describe --tags) && \
    go build -a -trimpath -ldflags="-s -w -X main.version=${VERSION}" -o /opt/agent


FROM debian:stable-slim

ENV TZ="Asia/Shanghai"

RUN apt-get update && \
    apt-get install -y --no-install-recommends tzdata ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /opt/agent /nezha/

ENTRYPOINT ["/nezha/agent"]